apiVersion: v1
kind: Service
metadata:
  name: {{ include "btfs-node.fullname" . }}
  labels:
    {{- include "btfs-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
    - port: 8080

  selector:
    {{- include "btfs-node.selectorLabels" . | nindent 4 }}
