apiVersion: v1
kind: Service
metadata:
  name: {{ include "btfs-node.fullname" . }}
  labels:
    {{- include "btfs-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5001
      name: dashboard
      targetPort: 5001
    - port: 8080
      name: gateway
      targetPort: 8080

  selector:
    {{- include "btfs-node.selectorLabels" . | nindent 4 }}
